AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an EC2 instance which enables SSH connection. 

Resources:
  DockerEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0947d2ba12ee1ff75
      InstanceType: t2.micro
      KeyName: secure
      SecurityGroups: 
        - !Ref DockerInstanceSecGrp
      Tags:
        - Key: Name 
          Value: DockerInstance
      UserData:
        Fn::Base64:
          !Sub | 
            #! /bin/bash
            yum update -y
            amazon-linux-extras install docker -y 
            service docker start
            usermod -a -G docker ec2-user
            newgrp docker
  DockerInstanceSecGrp:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allow Http and SSH port from anywhere #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80 
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22 
          ToPort: 22
          CidrIp: 0.0.0.0/0
  


